name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        user: ${{ secrets.user }}
        password: ${{ secrets.password }} 
      run: |
        echo $user
        echo $password
        docker build . --file Dockerfile --tag anas1337/dcm_webserver
        docker login -u $user -p $password
        docker push anas1337/dcm_webserver
